/*
 * Copyright 2017 Stella Filippo.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package View;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Stella Filippo
 * @version 0.01
 */
public class MainFrame extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form MainFram
     */
    public MainFrame() {
        super("Gestione Concessionaria");
        this.initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.initPanels();
        this.ToggleMenu.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioGroupStato = new javax.swing.ButtonGroup();
        Header = new javax.swing.JPanel();
        ToggleMenu = new javax.swing.JButton();
        User = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Footer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Welcome = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Modifica = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        Vendita = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Lista_Vendita = new javax.swing.JList<>();
        Stampa = new javax.swing.JPanel();
        Label_Stampa = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lista_Stampa = new javax.swing.JList<>();
        Aggiunta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Menu = new javax.swing.JPanel();
        MButton_Aggiungi = new javax.swing.JButton();
        MButton_Modifica = new javax.swing.JButton();
        MButton_Nuovi = new javax.swing.JButton();
        MButton_Usati = new javax.swing.JButton();
        MButton_Vendita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(841, 624));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        Header.setBackground(new java.awt.Color(0, 113, 156));
        Header.setPreferredSize(new java.awt.Dimension(800, 60));

        ToggleMenu.setBackground(new java.awt.Color(0, 113, 156));
        ToggleMenu.setForeground(new java.awt.Color(255, 255, 255));
        ToggleMenu.setText("Menu");
        ToggleMenu.setBorder(null);
        ToggleMenu.setBorderPainted(false);
        ToggleMenu.setFocusPainted(false);
        ToggleMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ToggleMenu.setOpaque(false);
        ToggleMenu.setVerifyInputWhenFocusTarget(false);

        User.setBackground(new java.awt.Color(0, 113, 156));
        User.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        User.setText("Concessionario Utente");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ToggleMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User)
                    .addComponent(ToggleMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 17, Short.MAX_VALUE))
        );

        jLayeredPane1.setMinimumSize(new java.awt.Dimension(800, 540));
        jLayeredPane1.setName(""); // NOI18N

        Footer.setBackground(new java.awt.Color(0, 113, 156));
        Footer.setForeground(new java.awt.Color(208, 208, 208));
        Footer.setFocusable(false);
        Footer.setPreferredSize(new java.awt.Dimension(834, 20));
        Footer.setRequestFocusEnabled(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(208, 208, 208));
        jLabel9.setText("Logger");
        jLabel9.setFocusable(false);
        jLabel9.setRequestFocusEnabled(false);

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                .addContainerGap())
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Welcome.setBackground(new java.awt.Color(77, 77, 77));
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setMinimumSize(new java.awt.Dimension(800, 540));
        Welcome.setPreferredSize(new java.awt.Dimension(841, 546));

        jLabel13.setBackground(new java.awt.Color(77, 77, 77));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(208, 208, 208));
        jLabel13.setText("Benvenuto Utente");
        jLabel13.setFocusable(false);
        jLabel13.setRequestFocusEnabled(false);

        jLabel15.setBackground(new java.awt.Color(77, 77, 77));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(208, 208, 208));
        jLabel15.setText("Per iniziare seleziona un'attività dal menù a sinistra");
        jLabel15.setFocusable(false);
        jLabel15.setRequestFocusEnabled(false);

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel15))
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel13)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel13)
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        Modifica.setBackground(new java.awt.Color(77, 77, 77));
        Modifica.setForeground(new java.awt.Color(255, 255, 255));
        Modifica.setMinimumSize(new java.awt.Dimension(800, 540));
        Modifica.setPreferredSize(new java.awt.Dimension(841, 546));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(208, 208, 208));
        jLabel16.setText("Modifica Automobile Usata");

        jScrollPane4.setBackground(new java.awt.Color(77, 77, 77));
        jScrollPane4.setBorder(null);
        jScrollPane4.setForeground(new java.awt.Color(208, 208, 208));

        jList2.setBackground(new java.awt.Color(77, 77, 77));
        jList2.setForeground(new java.awt.Color(208, 208, 208));
        jScrollPane4.setViewportView(jList2);

        jLabel17.setBackground(new java.awt.Color(77, 77, 77));
        jLabel17.setForeground(new java.awt.Color(208, 208, 208));
        jLabel17.setText("Automobile");

        jScrollPane6.setBackground(new java.awt.Color(77, 77, 77));
        jScrollPane6.setBorder(null);
        jScrollPane6.setForeground(new java.awt.Color(208, 208, 208));

        jList3.setBackground(new java.awt.Color(77, 77, 77));
        jList3.setForeground(new java.awt.Color(208, 208, 208));
        jScrollPane6.setViewportView(jList3);

        jLabel18.setBackground(new java.awt.Color(77, 77, 77));
        jLabel18.setForeground(new java.awt.Color(208, 208, 208));
        jLabel18.setText("Accessori");

        jComboBox4.setBackground(new java.awt.Color(77, 77, 77));
        jComboBox4.setForeground(new java.awt.Color(208, 208, 208));
        jComboBox4.setBorder(null);

        jButton3.setBackground(new java.awt.Color(0, 113, 156));
        jButton3.setForeground(new java.awt.Color(208, 208, 208));
        jButton3.setText("Aggiungi");
        jButton3.setBorder(null);

        javax.swing.GroupLayout ModificaLayout = new javax.swing.GroupLayout(Modifica);
        Modifica.setLayout(ModificaLayout);
        ModificaLayout.setHorizontalGroup(
            ModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificaLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ModificaLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(ModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ModificaLayout.createSequentialGroup()
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(ModificaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(307, 307, 307))))
        );
        ModificaLayout.setVerticalGroup(
            ModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificaLayout.createSequentialGroup()
                        .addComponent(jScrollPane6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox4)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Vendita.setBackground(new java.awt.Color(77, 77, 77));
        Vendita.setForeground(new java.awt.Color(255, 255, 255));
        Vendita.setMinimumSize(new java.awt.Dimension(800, 540));
        Vendita.setPreferredSize(new java.awt.Dimension(841, 546));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(208, 208, 208));
        jLabel14.setText("Vendita Automobile");

        jButton1.setBackground(new java.awt.Color(0, 113, 156));
        jButton1.setForeground(new java.awt.Color(208, 208, 208));
        jButton1.setText("Vendi");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);

        jScrollPane5.setBackground(new java.awt.Color(77, 77, 77));
        jScrollPane5.setBorder(null);
        jScrollPane5.setForeground(new java.awt.Color(208, 208, 208));

        Lista_Vendita.setBackground(new java.awt.Color(77, 77, 77));
        Lista_Vendita.setForeground(new java.awt.Color(208, 208, 208));
        jScrollPane5.setViewportView(Lista_Vendita);

        javax.swing.GroupLayout VenditaLayout = new javax.swing.GroupLayout(Vendita);
        Vendita.setLayout(VenditaLayout);
        VenditaLayout.setHorizontalGroup(
            VenditaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenditaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(VenditaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        VenditaLayout.setVerticalGroup(
            VenditaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenditaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Stampa.setBackground(new java.awt.Color(77, 77, 77));
        Stampa.setForeground(new java.awt.Color(255, 255, 255));
        Stampa.setMinimumSize(new java.awt.Dimension(800, 540));
        Stampa.setPreferredSize(new java.awt.Dimension(841, 546));

        Label_Stampa.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label_Stampa.setForeground(new java.awt.Color(208, 208, 208));
        Label_Stampa.setText("Lista Automobili");

        jScrollPane3.setBackground(new java.awt.Color(77, 77, 77));
        jScrollPane3.setBorder(null);
        jScrollPane3.setForeground(new java.awt.Color(208, 208, 208));

        Lista_Stampa.setBackground(new java.awt.Color(77, 77, 77));
        Lista_Stampa.setForeground(new java.awt.Color(208, 208, 208));
        jScrollPane3.setViewportView(Lista_Stampa);

        javax.swing.GroupLayout StampaLayout = new javax.swing.GroupLayout(Stampa);
        Stampa.setLayout(StampaLayout);
        StampaLayout.setHorizontalGroup(
            StampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StampaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(StampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Stampa)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        StampaLayout.setVerticalGroup(
            StampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StampaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Label_Stampa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Aggiunta.setBackground(new java.awt.Color(77, 77, 77));
        Aggiunta.setForeground(new java.awt.Color(255, 255, 255));
        Aggiunta.setMinimumSize(new java.awt.Dimension(800, 540));
        Aggiunta.setPreferredSize(new java.awt.Dimension(841, 546));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(208, 208, 208));
        jLabel2.setText("Aggiungi Automobile");

        jLabel3.setForeground(new java.awt.Color(208, 208, 208));
        jLabel3.setText("Marca");

        jTextField1.setBackground(new java.awt.Color(77, 77, 77));
        jTextField1.setForeground(new java.awt.Color(208, 208, 208));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(208, 208, 208));
        jTextField1.setOpaque(false);

        jLabel4.setForeground(new java.awt.Color(208, 208, 208));
        jLabel4.setText("Tipo");

        jLabel5.setForeground(new java.awt.Color(208, 208, 208));
        jLabel5.setText("Alimentazione");

        jTextField4.setBackground(new java.awt.Color(77, 77, 77));
        jTextField4.setForeground(new java.awt.Color(208, 208, 208));
        jTextField4.setBorder(null);
        jTextField4.setCaretColor(new java.awt.Color(208, 208, 208));
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator3.setBackground(new java.awt.Color(77, 77, 77));
        jSeparator3.setForeground(new java.awt.Color(208, 208, 208));

        jLabel6.setForeground(new java.awt.Color(208, 208, 208));
        jLabel6.setText("Stato");

        jRadioButton1.setBackground(new java.awt.Color(77, 77, 77));
        RadioGroupStato.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(208, 208, 208));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Nuovo");
        jRadioButton1.setBorder(null);
        jRadioButton1.setFocusPainted(false);

        jRadioButton2.setBackground(new java.awt.Color(77, 77, 77));
        RadioGroupStato.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(208, 208, 208));
        jRadioButton2.setText("Usato");
        jRadioButton2.setBorder(null);
        jRadioButton2.setFocusPainted(false);

        jLabel7.setBackground(new java.awt.Color(77, 77, 77));
        jLabel7.setForeground(new java.awt.Color(208, 208, 208));
        jLabel7.setText("Mese");

        jComboBox1.setBackground(new java.awt.Color(77, 77, 77));
        jComboBox1.setForeground(new java.awt.Color(208, 208, 208));
        jComboBox1.setModel(this.generaMesi());
        jComboBox1.setBorder(null);
        jComboBox1.setEnabled(false);
        jComboBox1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(208, 208, 208));
        jLabel1.setText("Anno");

        jComboBox2.setBackground(new java.awt.Color(77, 77, 77));
        jComboBox2.setForeground(new java.awt.Color(208, 208, 208));
        jComboBox2.setModel(this.generaAnni());
        jComboBox2.setBorder(null);
        jComboBox2.setEnabled(false);
        jComboBox2.setOpaque(false);

        jLabel8.setForeground(new java.awt.Color(208, 208, 208));
        jLabel8.setText("Prezzo");

        jTextField3.setBackground(new java.awt.Color(77, 77, 77));
        jTextField3.setForeground(new java.awt.Color(208, 208, 208));
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(208, 208, 208));

        jSeparator4.setBackground(new java.awt.Color(77, 77, 77));
        jSeparator4.setForeground(new java.awt.Color(208, 208, 208));

        jLabel10.setForeground(new java.awt.Color(208, 208, 208));
        jLabel10.setText("Accessori");

        jScrollPane1.setBackground(new java.awt.Color(77, 77, 77));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(208, 208, 208));
        jScrollPane1.setRequestFocusEnabled(false);

        jList1.setBackground(new java.awt.Color(77, 77, 77));
        jList1.setForeground(new java.awt.Color(208, 208, 208));
        jList1.setSelectionBackground(new java.awt.Color(0, 113, 156));
        jList1.setSelectionForeground(new java.awt.Color(208, 208, 208));
        jScrollPane1.setViewportView(jList1);

        jComboBox3.setBackground(new java.awt.Color(77, 77, 77));
        jComboBox3.setForeground(new java.awt.Color(208, 208, 208));
        jComboBox3.setBorder(null);

        jButton2.setBackground(new java.awt.Color(0, 113, 156));
        jButton2.setForeground(new java.awt.Color(208, 208, 208));
        jButton2.setText("Aggiungi");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel11.setForeground(new java.awt.Color(208, 208, 208));
        jLabel11.setText("Immagine");

        jTextField5.setBackground(new java.awt.Color(77, 77, 77));
        jTextField5.setForeground(new java.awt.Color(208, 208, 208));
        jTextField5.setText("Seleziona Un Immagine...");
        jTextField5.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(77, 77, 77));
        jSeparator5.setForeground(new java.awt.Color(208, 208, 208));

        jSeparator6.setBackground(new java.awt.Color(77, 77, 77));
        jSeparator6.setForeground(new java.awt.Color(208, 208, 208));

        jSeparator8.setBackground(new java.awt.Color(77, 77, 77));
        jSeparator8.setForeground(new java.awt.Color(208, 208, 208));

        jScrollPane2.setBackground(new java.awt.Color(77, 77, 77));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(208, 208, 208));

        jLabel12.setBackground(new java.awt.Color(77, 77, 77));
        jLabel12.setForeground(new java.awt.Color(208, 208, 208));
        jLabel12.setText("Image");
        jLabel12.setToolTipText("");
        jLabel12.setOpaque(true);
        jScrollPane2.setViewportView(jLabel12);

        jTextField2.setBackground(new java.awt.Color(77, 77, 77));
        jTextField2.setForeground(new java.awt.Color(208, 208, 208));
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(208, 208, 208));
        jTextField2.setOpaque(false);

        javax.swing.GroupLayout AggiuntaLayout = new javax.swing.GroupLayout(Aggiunta);
        Aggiunta.setLayout(AggiuntaLayout);
        AggiuntaLayout.setHorizontalGroup(
            AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AggiuntaLayout.createSequentialGroup()
                .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AggiuntaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(AggiuntaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AggiuntaLayout.createSequentialGroup()
                                .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jTextField4)
                                    .addComponent(jSeparator8)))
                            .addGroup(AggiuntaLayout.createSequentialGroup()
                                .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(AggiuntaLayout.createSequentialGroup()
                                        .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField3)
                                            .addComponent(jSeparator4)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addGroup(AggiuntaLayout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButton2))
                                            .addComponent(jComboBox1, 0, 300, Short.MAX_VALUE)
                                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jSeparator6)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                            .addGroup(AggiuntaLayout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AggiuntaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        AggiuntaLayout.setVerticalGroup(
            AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AggiuntaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AggiuntaLayout.createSequentialGroup()
                        .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton2))
                        .addGap(10, 10, 10)
                        .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AggiuntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        Menu.setBackground(new java.awt.Color(0, 113, 156));
        Menu.setMinimumSize(new java.awt.Dimension(0, 540));
        Menu.setPreferredSize(new java.awt.Dimension(250, 540));
        Menu.setRequestFocusEnabled(false);

        MButton_Aggiungi.setBackground(new java.awt.Color(0, 113, 156));
        MButton_Aggiungi.setForeground(new java.awt.Color(255, 255, 255));
        MButton_Aggiungi.setText("Aggiungi Automobile");
        MButton_Aggiungi.setBorder(null);
        MButton_Aggiungi.setBorderPainted(false);
        MButton_Aggiungi.setFocusPainted(false);

        MButton_Modifica.setBackground(new java.awt.Color(0, 113, 156));
        MButton_Modifica.setForeground(new java.awt.Color(255, 255, 255));
        MButton_Modifica.setText("Modifca Automobile Usata");
        MButton_Modifica.setBorder(null);
        MButton_Modifica.setBorderPainted(false);
        MButton_Modifica.setFocusPainted(false);

        MButton_Nuovi.setBackground(new java.awt.Color(0, 113, 156));
        MButton_Nuovi.setForeground(new java.awt.Color(255, 255, 255));
        MButton_Nuovi.setText("Lista Nuovo");
        MButton_Nuovi.setBorder(null);
        MButton_Nuovi.setBorderPainted(false);
        MButton_Nuovi.setFocusPainted(false);

        MButton_Usati.setBackground(new java.awt.Color(0, 113, 156));
        MButton_Usati.setForeground(new java.awt.Color(255, 255, 255));
        MButton_Usati.setText("Lista Usato");
        MButton_Usati.setBorder(null);
        MButton_Usati.setBorderPainted(false);
        MButton_Usati.setFocusPainted(false);

        MButton_Vendita.setBackground(new java.awt.Color(0, 113, 156));
        MButton_Vendita.setForeground(new java.awt.Color(255, 255, 255));
        MButton_Vendita.setText("Vendita Automobile");
        MButton_Vendita.setBorder(null);
        MButton_Vendita.setBorderPainted(false);
        MButton_Vendita.setFocusPainted(false);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MButton_Modifica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(MButton_Aggiungi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MButton_Nuovi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MButton_Usati, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MButton_Vendita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(MButton_Aggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(MButton_Nuovi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MButton_Usati, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(MButton_Vendita, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MButton_Modifica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(Footer, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.setLayer(Welcome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Modifica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Vendita, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Stampa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Aggiunta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Menu, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Aggiunta, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Stampa, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Vendita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Modifica, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Aggiunta, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Stampa, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Vendita, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Modifica, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 544, Short.MAX_VALUE)
                    .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initPanels(){
        this.Stampa.setVisible(false);
        this.Aggiunta.setVisible(false);
        this.Modifica.setVisible(false);
        this.Vendita.setVisible(false);
        this.Welcome.setVisible(true);
    }

    public JButton getToggleMenu() {
        return ToggleMenu;
    }
    public JPanel getMenu() {
        return Menu;
    }
    public JPanel getAggiunta() {
        return Aggiunta;
    }
    public JPanel getFooter() {
        return Footer;
    }
    public JPanel getHeader() {
        return Header;
    }
    public JButton getMButton_Aggiungi() {
        return MButton_Aggiungi;
    }
    public JButton getMButton_Modifica() {
        return MButton_Modifica;
    }
    public JButton getMButton_Nuovi() {
        return MButton_Nuovi;
    }
    public JButton getMButton_Usati() {
        return MButton_Usati;
    }
    public JButton getMButton_Vendita() {
        return MButton_Vendita;
    }
    public JPanel getModifica() {
        return Modifica;
    }
    public JPanel getStampa() {
        return Stampa;
    }
    public JPanel getVendita() {
        return Vendita;
    }
    public JPanel getWelcome() {
        return Welcome;
    }
    
    public void ToggleMenu(){
        if(this.menuStatus){
            this.executor.execute(new CloseMenu(this));
            this.menuStatus = false;
        }
        else{
            this.executor.execute(new OpenMenu(this));
            this.menuStatus = true;
        }
    }
    
    public DefaultComboBoxModel generaAnni(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for(int i=1950;i<Calendar.getInstance().get(Calendar.YEAR);i++){
            model.addElement(""+i);
        }
        return model;
    }
    
    public DefaultComboBoxModel generaMesi(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Gennaio");
        model.addElement("Fabbraio");
        model.addElement("Marzo");
        model.addElement("Aprile");
        model.addElement("Maggio");
        model.addElement("Giugno");
        model.addElement("Luglio");
        model.addElement("Agosto");
        model.addElement("Settembre");
        model.addElement("Ottobre");
        model.addElement("Novembre");
        model.addElement("Dicembre");
        return model;
    }
    
   public void setActionMenuButton(ActionListener al){
       this.MButton_Aggiungi.addActionListener(al);
       this.MButton_Modifica.addActionListener(al);
       this.MButton_Nuovi.addActionListener(al);
       this.MButton_Usati.addActionListener(al);
       this.MButton_Vendita.addActionListener(al);
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Aggiunta;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Label_Stampa;
    private javax.swing.JList<String> Lista_Stampa;
    private javax.swing.JList<String> Lista_Vendita;
    private javax.swing.JButton MButton_Aggiungi;
    private javax.swing.JButton MButton_Modifica;
    private javax.swing.JButton MButton_Nuovi;
    private javax.swing.JButton MButton_Usati;
    private javax.swing.JButton MButton_Vendita;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Modifica;
    private javax.swing.ButtonGroup RadioGroupStato;
    private javax.swing.JPanel Stampa;
    private javax.swing.JButton ToggleMenu;
    private javax.swing.JLabel User;
    private javax.swing.JPanel Vendita;
    private javax.swing.JPanel Welcome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
    private final Executor executor = Executors.newSingleThreadExecutor();
    private boolean menuStatus = true;
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==this.ToggleMenu){
            this.ToggleMenu.setEnabled(false);
            this.ToggleMenu();
        }
        else{
            throw new UnsupportedOperationException("Not supported yet.");
        }
    }
}

class OpenMenu extends Thread{

    private final MainFrame mf;
    
    public OpenMenu(MainFrame mf) {
        super("ApriMenu");
        this.mf = mf;
    }

    @Override
    public void run() {
        JPanel menu = this.mf.getMenu();
        synchronized (menu){
            while(menu.getWidth()<250){
                try {
                    menu.setPreferredSize(new Dimension(menu.getWidth()+1, menu.getHeight()));
                    menu.revalidate();
                    menu.repaint();
                    sleep(0,3);
                } catch (InterruptedException ex) {
                    Logger.getLogger(OpenMenu.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
            this.mf.getToggleMenu().setEnabled(true);
        }
    }
    
}

class CloseMenu extends Thread{
    
    private final MainFrame mf;
    
    public CloseMenu(MainFrame mf) {
        super("ChiudiMenu");
        this.mf = mf;
    }

    @Override
    public void run() {
        JPanel menu = this.mf.getMenu();
        synchronized (menu){
            while(menu.getWidth()>0){
                try {
                    menu.setPreferredSize(new Dimension(menu.getWidth()-1, menu.getHeight()));
                    menu.revalidate();
                    menu.repaint();
                    sleep(0,3);
                } catch (InterruptedException ex) {
                    Logger.getLogger(OpenMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            this.mf.getToggleMenu().setEnabled(true);
        }
    }

}